services:
  miner:
    container_name: miner
    restart: unless-stopped
    image: taofuprotocol/tpn-subnet-miner:latest
    ports:
        - "3001:3001"
    environment:
        LOG_LEVEL: info

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_TIMEOUT=60s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock